services:
  - type: web
    name: flask-todo-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: "0"
      - key: APP_SECRET_KEY
        generateValue: true
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_CALLBACK_URL
        sync: false
